### ISSUE TITLE
Working

### ISSUE THREAD

**Issue by AL-THE-BOT-FATHER** [DavidTaapy/Dex-Screener-Scraper#2]
Is this still working for you? 

Thanks!

**Comment by DavidTaapy** [comment]
Hi! I have just checked, there seems to be an issue with cloudflare and undetected-chromedriver! I am investigating it now!

**Comment by DavidTaapy** [comment]
Hi! I have changed from UC to SeleniumBase and the screener just worked for me! The new data file extracted is as follows!
[Data.csv](https://github.com/DavidTaapy/Dex-Screener-Scraper/files/12170994/Data.csv)
